### ISSUE TITLE
[RFC] 21. Data Actions 

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/open-app-builder#2515]
## Summary
Summary of key action points for [RFC 21. Data Actions](https://docs.google.com/document/d/1qJi9Nk--CFwGTPMn9ksmOgoVq_dnXrTMlN9a_i7kUyY/edit?tab=t.0#heading=h.z1slo8oiq52p)

## Tasks
- [x] `set_data` standalone action #2513
- [x] Data list row modifiers (add/remove rows) #2625
- [ ] Data query syntax and advanced operators
- [ ] Action query syntax to alter which data action applied to (e.g. sort, filter, limit)

## Related issues
- #2500 
- #2476
- #2524 

## Additional tasks from PRs
- [ ] Support for author-defined schema and validation on data_lists (e.g. first row metadata)

## Documentation Requirements
- [ ] Use cases for `set_data` action
