### ISSUE TITLE
[RFC] 23. Data Privacy

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/open-app-builder#2516]
## Summary
Summary of key action points for [RFC 23. Data Privacy](https://docs.google.com/document/d/1i3OQRz3FwdwrOahGWE6rAWGQ2twhN8gWy8LxPzzUT1I/edit?tab=t.0#heading=h.nd960lmg5uuf)

## Tasks
**Phase 1**
- [ ] Deployment config support for runtime encryption config (enabled, public key)
- [ ] Action to `set_field_encrypted`
- [ ] Field service update to store value with metadata
- [ ] (potential) Migrate field service to store in indexeddb table instead of localstorage
- [ ] Field service update to encrypt values on demand
- [ ] Encryption service to handle 1-way encryption of sensitive data
- [ ] Server and sync updates to store both app_fields and app_fields_encrypted tables

**Phase 2**
- [ ] (To review)

**Related issues**
#2392
#2444

## Additional tasks from PRs
- [ ] ...

## Documentation Requirements
- [ ] ...
